version: '3.8'

services:
  api:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - api-php-fpm
    networks:
      - mynetwork

  api-php-fpm:
    build:
      context: docker
      dockerfile: php-fpm/Dockerfile
    volumes:
      - ./api:/var/www/api
    networks:
      - mynetwork
    depends_on:
      - storage
      - database

  api-php-cli:
    build:
      context: docker
      dockerfile: php-cli/Dockerfile
    tty: true
    restart: always
    volumes:
      - ./api:/var/www/api
    networks:
      - mynetwork
    depends_on:
      - storage
      - database

  database:
    image: postgres:16
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"
    networks:
      - mynetwork

  storage:
    build:
      context: ./docker/storage
    volumes:
      - ./storage:/app
    ports:
      - "8083:80"

  storage-ftp:
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: app
      FTP_USER_PASS: secret
      FTP_USER_HOME: /app
    volumes:
      - ./storage/public:/app
    networks:
      - mynetwork

volumes:
  postgres:

networks:
  mynetwork:
    driver: bridge