version: '3.8'

services:
  api:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    volumes:
      - ./api:/home/app
    ports:
      - "8081:80"
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: docker
      dockerfile: php-fpm/Dockerfile
    volumes:
      - ./api:/home/app

  api-php-cli:
    build:
      context: docker
      dockerfile: php-cli/Dockerfile
    tty: true
    restart: always
    volumes:
      - ./api:/home/app

  database:
    image: postgres:16
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

volumes:
  postgres: